---
title: " "
output: 
  html_document:
    toc: false 
    toc_float:
      toc_collapsed: false 
    toc_depth: 3
    number_sections: false 
---

---

### Educational Content

- [Introduction to Regularization](./posts/regularization/index.nb.html)
- [Analytics Concept Review](./posts/analytics_review/index.html)
- [Analytics Job Application](./posts/job_application/index.html)
- [Indeed.com Analytics Job Listing](./posts/job_listing/index.html)
- [Popular Analytics Tools](https://franklinanalytics.medium.com/a-brief-summary-for-popular-analytics-tools-7d7081051c5e)
- [Commonly-used R & Python Scripts for Data Wrangling](https://franklinanalytics.medium.com/side-by-side-data-wrangling-script-in-r-and-python-1e5ba4cfca04)
- [Popularity of Analytics Tools in Job Listings](./posts/analytics_tools/index.html)



### LinkedIn

- [Meet Advisory Board Member](https://www.linkedin.com/posts/jiang-li-analytics_analytics-datascience-education-activity-7220131677367365632-w1dG?utm_source=share&utm_medium=member_desktop)
- [DataFest 2024](https://www.linkedin.com/posts/jiang-li-analytics_datafest-analytics-franklinmakesitpossible-activity-7193410367404843010-JURv?utm_source=share&utm_medium=member_desktop)
- [Franklin University's Master’s in Business Analytics program has been ranked NO.8 by TechGuide](https://www.linkedin.com/posts/jiang-li-analytics_online-masters-in-business-analytics-programs-activity-7173688007168917505-Q0Tz?utm_source=share&utm_medium=member_desktop)
- [New B.S. in Analytics Program](https://www.linkedin.com/posts/jiang-li-analytics_i-am-thrilled-to-announce-that-i-have-successfully-activity-7141501606558150657-F4qK?utm_source=share&utm_medium=member_desktop)
- [DataConnect](https://www.linkedin.com/feed/update/urn:li:activity:7113175549455302658?utm_source=share&utm_medium=member_desktop)
- [Master of Science in Analytics Degree from Georgia Tech](https://www.linkedin.com/posts/jiang-li-analytics_with-a-phd-in-hand-i-returned-to-the-student-activity-7099368661798330369-9NUZ?utm_source=share&utm_medium=member_desktop)
- [Franklin University's STEM scholarship](https://www.linkedin.com/posts/jiang-li-analytics_education-studentfunding-highereducation-activity-7089986073245749248-eNWf?utm_source=share&utm_medium=member_desktop)
- [Data Science Prompts](https://www.linkedin.com/posts/jiang-li-analytics_60-chatgpt-prompts-for-data-science-tried-activity-7062425482922754048-Cebw?utm_source=share&utm_medium=member_desktop)
- [Introduction to Regularization](https://www.linkedin.com/posts/jiang-li-analytics_regularization-activity-7062111655052132353-I2AC?utm_source=share&utm_medium=member_desktop)
- [Analytics Job Application](https://www.linkedin.com/posts/jiang-li-analytics_analytics-job-application-activity-7039986766761627648-c1Ec?utm_source=share&utm_medium=member_desktop)
- [Heilmeier's Questions](https://www.linkedin.com/posts/jiang-li-analytics_defense-advanced-research-projects-agency-activity-7030970627498930176-rQai?utm_source=share&utm_medium=member_desktop)
- [Semantic Layer Summit](https://www.linkedin.com/feed/update/urn:li:activity:7021859651658940416?utm_source=share&utm_medium=member_desktop)
- [Useful Excel Functions](https://www.linkedin.com/feed/update/urn:li:activity:7017184076247826432?utm_source=share&utm_medium=member_desktop)
- [Inclusive Pedagogy](https://www.linkedin.com/posts/jiang-li-analytics_inclusive-pedagogy-was-issued-by-franklin-activity-7017133146064261121-i1Dj?utm_source=share&utm_medium=member_desktop)
- [Salary Information in the Industry](https://www.linkedin.com/posts/jiang-li-analytics_analytics-activity-7017125505195794432-gpLT?utm_source=share&utm_medium=member_desktop)
- [OpenAI's Response to "how to learn business analytics?"](https://www.linkedin.com/posts/jiang-li-analytics_openai-chatgpt-artificialintelligence-activity-7004815736527351808-WSNm?utm_source=share&utm_medium=member_desktop)
- [Cake from My Students](https://www.linkedin.com/posts/jiang-li-analytics_teaching-analytics-activity-6994052564870664192-cFFE?utm_source=share&utm_medium=member_desktop)
- [Job Listing Count On U.S. Map](https://www.linkedin.com/posts/jiang-li-analytics_analytics-job-listing-activity-6983991328804126720-h64-?utm_source=share&utm_medium=member_desktop)
- [Ohio First Scholarship](https://www.linkedin.com/posts/jiang-li-analytics_ohio-first-stem-scholarship-activity-6959947182766530560-GnDG?utm_source=share&utm_medium=member_desktop)
- [Companies don’t have datasets waiting for you](https://www.linkedin.com/posts/jiang-li-analytics_machinelearning-data-datascience-activity-6938188158635294720-N-qr?utm_source=share&utm_medium=member_desktop)
- [DataFest 2022 Winners](https://www.linkedin.com/posts/jiang-li-analytics_congratulations-to-the-winning-team-of-franklin-activity-6928436032707190784-hbCW?utm_source=share&utm_medium=member_desktop)
- [Common Mistates of SQL JOIN](https://www.linkedin.com/feed/update/urn:li:activity:6922909309630631936?utm_source=share&utm_medium=member_desktop)
- [An Intuitive Visualization of SQL JOIN](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6920733422604701696-uGIp?utm_source=share&utm_medium=member_desktop)
- [McGraw Hill Business Analytics Summit 2022](https://www.linkedin.com/posts/jiang-li-analytics_businessanalytics-teaching-education-activity-6912400227819794433-cCMH?utm_source=share&utm_medium=member_desktop)
- [Teach International Students from India](https://www.linkedin.com/posts/jiang-li-analytics_franklinmakesitpossible-2022ready-education-activity-6883931401910005760-a13a?utm_source=share&utm_medium=member_desktop)
- [Convert English Language to Python](https://www.linkedin.com/posts/jiang-li-analytics_innovation-artificialintelligence-deeplearning-activity-6880653855856566272-abA2?utm_source=share&utm_medium=member_desktop)
- [Commonly-used Analytics Tools](https://www.linkedin.com/posts/jiang-li-analytics_a-brief-summary-for-popular-analytics-tools-activity-6877651936670208000-n4qq?utm_source=share&utm_medium=member_desktop)
- [DATA 300: Introduction to Analytics](https://www.linkedin.com/posts/jiang-li-analytics_datawrangling-datavisualization-regressionanalysis-activity-6863938185991372800-4O2c)
- [Data Science in 2021](https://www.linkedin.com/posts/jiang-li-analytics_state-of-data-science-in-2021-activity-6843222852242608128-yj6H)
- [Ed Discussion Tool](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6839630323928612864-MaJu)
- [Correlation vs. causation](https://www.linkedin.com/posts/jiang-li-analytics_bad-credit-or-no-credit-shouldnt-affect-activity-6831660659332198400-AkhL)
- [Product Analyst Role](https://www.linkedin.com/posts/jiang-li-analytics_product-analysts-what-is-that-activity-6828681711170199552-IwdX)
- [A/B Testing](https://www.linkedin.com/posts/jiang-li-analytics_the-art-of-ab-testing-activity-6824374446371979264-SLOu)
- [Free courses in LinkedIn Learning](https://www.linkedin.com/posts/jiang-li-analytics_businessanalysis-personalgrowth-professionaldevelopment-activity-6800186575796924416-qv0E)
- [Redesign DATA 610](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6798960640217145344-hmrk)
- [AWS Cloud](https://www.linkedin.com/feed/update/urn:li:activity:6777254912163151872)
- [DataFest 2021](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6773637143085535233-ZF_N)
- [Domain Knowledge](https://www.linkedin.com/posts/jiang-li-analytics_domain-expertisewhy-is-it-important-for-activity-6767871834760257536-MrM7)
- [SQL Data Duplication](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6764940052565946368-mMkJ)
- [RStudio::global 2021](https://www.linkedin.com/posts/jiang-li-analytics_rstudio-webinars-activity-6763195681315405824-fRGt)
- [Analytics Reporting](https://www.linkedin.com/posts/jiang-li-analytics_introduction-activity-6760577606216667136-Te0r)
- [Key Data Science Concepts for Interview](https://www.linkedin.com/posts/jiang-li-analytics_crack-data-science-interviews-essential-activity-6758912449774186496-T28o)
- [Welcome Dr. Vesselinov](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6755892965622784000-t2KF)
- [Essential SQL Concepts](https://www.linkedin.com/posts/jiang-li-analytics_ten-sql-concepts-you-should-know-for-data-activity-6745372255187976193-dsjC)
- [Highlighted Analtyics Skills](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6741815732910247936-IVuM)
- [AWS Big Data Event](https://www.linkedin.com/posts/jiang-li-analytics_aws-reinvent-activity-6739676099229364224-XDAN)
- [Confidence Interval](https://www.linkedin.com/posts/jiang-li-analytics_calculating-confidence-interval-with-bootstrapping-activity-6737369570543325184-TJaq)
- [Suggestion to students: get hands dirty](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6735202069420003329-7Btr)
- [Data Cleaning](https://www.linkedin.com/feed/update/urn:li:activity:6735025440374751233)
- [Suggestion to students: be a problem solver](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6734883890625867776-zWJO)
- [Suggestion to students: continue being curious](https://www.linkedin.com/posts/jiang-li-analytics_personalgrowth-professionaldevelopment-education-activity-6734482946864025600-KP-3)
- [Data Science Thinking: a case study](https://www.linkedin.com/feed/update/urn:li:activity:6702219196111097856)

